SET LINESIZE 150
SET PAGESIZE 100

-- 1. Overall KPIs
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY_KWH,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY_KWH,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY_KWH,
    ROUND(AVG(CO2_TCO2), 4) AS AVG_CO2
FROM energy_consumption;


-- 2. Monthly consumption
SELECT
    MONTH,
    MONTH_NAME,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY MONTH, MONTH_NAME
ORDER BY MONTH;


-- 3. Hourly consumption
SELECT
    HOUR,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY HOUR
ORDER BY HOUR;


-- 4. Load type analysis
SELECT
    LOAD_TYPE,
    COUNT(*) AS RECORDS,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY LOAD_TYPE
ORDER BY AVG_ENERGY DESC;


-- 5. Weekday vs weekend
SELECT
    WEEK_STATUS,
    COUNT(*) AS RECORDS,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY WEEK_STATUS;


-- 6. Day of week
SELECT
    DAY_OF_WEEK_NUMBER,
    DAY_OF_WEEK,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY DAY_OF_WEEK_NUMBER, DAY_OF_WEEK
ORDER BY DAY_OF_WEEK_NUMBER;


-- 7. Time period
SELECT
    TIME_PERIOD,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY TIME_PERIOD
ORDER BY AVG_ENERGY DESC;


-- 8. Load type vs week status
SELECT
    LOAD_TYPE,
    WEEK_STATUS,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY
FROM energy_consumption
GROUP BY LOAD_TYPE, WEEK_STATUS
ORDER BY AVG_ENERGY DESC;


-- 9. Load type vs time period
SELECT
    LOAD_TYPE,
    TIME_PERIOD,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(MAX(ENERGY_CONSUMPTION_KWH), 2) AS PEAK_ENERGY
FROM energy_consumption
GROUP BY LOAD_TYPE, TIME_PERIOD
ORDER BY AVG_ENERGY DESC;


-- 10. Highest consumption periods
SELECT
    DATETIME,
    ENERGY_CONSUMPTION_KWH,
    LOAD_TYPE,
    WEEK_STATUS,
    DAY_OF_WEEK,
    HOUR,
    TIME_PERIOD,
    CO2_TCO2
FROM energy_consumption
ORDER BY ENERGY_CONSUMPTION_KWH DESC
FETCH FIRST 20 ROWS ONLY;


-- 11. Potential anomalies
SELECT
    DATETIME,
    ENERGY_CONSUMPTION_KWH,
    LOAD_TYPE,
    WEEK_STATUS,
    DAY_OF_WEEK,
    HOUR,
    TIME_PERIOD,
    CO2_TCO2
FROM energy_consumption
WHERE ENERGY_CONSUMPTION_KWH > 123.29375
ORDER BY ENERGY_CONSUMPTION_KWH DESC;


-- 12. Anomaly count by load type
SELECT
    LOAD_TYPE,
    COUNT(*) AS ANOMALY_COUNT,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ANOMALY_ENERGY
FROM energy_consumption
WHERE ENERGY_CONSUMPTION_KWH > 123.29375
GROUP BY LOAD_TYPE
ORDER BY ANOMALY_COUNT DESC;


-- 13. Anomaly count by hour
SELECT
    HOUR,
    COUNT(*) AS ANOMALY_COUNT,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ANOMALY_ENERGY
FROM energy_consumption
WHERE ENERGY_CONSUMPTION_KWH > 123.29375
GROUP BY HOUR
ORDER BY ANOMALY_COUNT DESC;


-- 14. Energy vs CO2
SELECT
    LOAD_TYPE,
    ROUND(AVG(ENERGY_CONSUMPTION_KWH), 2) AS AVG_ENERGY,
    ROUND(AVG(CO2_TCO2), 4) AS AVG_CO2,
    ROUND(SUM(CO2_TCO2), 4) AS TOTAL_CO2
FROM energy_consumption
GROUP BY LOAD_TYPE
ORDER BY AVG_ENERGY DESC;


-- 15. Monthly energy and CO2
SELECT
    YEAR,
    MONTH,
    MONTH_NAME,
    ROUND(SUM(ENERGY_CONSUMPTION_KWH), 2) AS TOTAL_ENERGY,
    ROUND(SUM(CO2_TCO2), 4) AS TOTAL_CO2
FROM energy_consumption
GROUP BY YEAR, MONTH, MONTH_NAME
ORDER BY YEAR, MONTH;